// Generated by CoffeeScript 1.6.3
(function() {
  Calendar.Router.map('Calendar', {
    path: '/'
  }, function() {});

  Calendar.CalendarRoute = Ember.Route.extend();

  Calendar.CalendarIndexRoute = Ember.Route.extend();

}).call(this);
