// Generated by CoffeeScript 1.6.3
(function() {
  Calendar.Router.map(function() {
    return this.resource('Calendar', {
      path: '/'
    });
  });

  Calendar.CalendarRoute = Ember.Route.extend();

  Calendar.CalendarIndexRoute = Ember.Route.extend();

}).call(this);
