// Generated by CoffeeScript 1.6.3
(function() {
  Array.prototype.chunk = function(pieces) {
    var chunks, i, last, len, mid, start, _i;
    pieces = pieces || 2;
    len = this.length;
    mid = len / pieces;
    chunks = [];
    start = 0;
    for (i = _i = 0; 0 <= pieces ? _i <= pieces : _i >= pieces; i = 0 <= pieces ? ++_i : --_i) {
      last = start + mid;
      if (!len % pieces >= i) {
        last = last - 1;
      }
      chunks.push(this.slice(start, last + 1) || []);
      start = last + 1;
    }
    return chunks;
  };

}).call(this);
