// Generated by CoffeeScript 1.6.3
(function() {
  Date.prototype.getMonthName = function() {
    var month;
    month = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'];
    return month[this.getMonth()];
  };

}).call(this);
