// Generated by CoffeeScript 1.6.3
(function() {
  Calendar.CalendarController = Ember.ObjectController.extend({
    selectedDay: 21,
    selectedMonth: 10,
    selectedYear: 2013,
    getDays: (function() {
      var day, days, daysInMonth, daysInPrevMonth, endDay, i, nowDate, selectedDate, startDay, _i, _j, _k, _ref, _ref1;
      nowDate = new Date(new Date().getFullYear(), new Date().getMonth(), new Date().getDate());
      selectedDate = new Date(this.get('selectedYear'), this.get('selectedMonth') - 1, this.get('selectedDay'));
      daysInMonth = 32 - new Date(this.get('selectedYear'), this.get('selectedMonth') - 1, 32).getDate();
      daysInPrevMonth = 32 - new Date(this.get('selectedYear'), this.get('selectedMonth') - 2, 32).getDate();
      startDay = new Date(this.get('selectedYear'), this.get('selectedMonth') - 1, 0).getDay();
      endDay = new Date(this.get('selectedYear'), this.get('selectedMonth'), 0).getDay();
      days = [];
      day = new Object();
      day.dayClass = '';
      day.dayNum = endDay;
      for (i = _i = _ref = startDay - 1; _ref <= 0 ? _i <= 0 : _i >= 0; i = _ref <= 0 ? ++_i : --_i) {
        day = new Object;
        day.dayClass = 'anotherDay';
        day.dayNum = daysInPrevMonth - i;
        days.push(day);
      }
      for (i = _j = 1; 1 <= daysInMonth ? _j <= daysInMonth : _j >= daysInMonth; i = 1 <= daysInMonth ? ++_j : --_j) {
        day = new Object;
        if (selectedDate === nowDate) {
          day.dayClass = 'now';
        } else {
          day.dayClass = 'dayOfMonth';
        }
        day.dayNum = i;
        days.push(day);
      }
      for (i = _k = 1, _ref1 = 7 - endDay; 1 <= _ref1 ? _k <= _ref1 : _k >= _ref1; i = 1 <= _ref1 ? ++_k : --_k) {
        day = new Object;
        day.dayClass = 'anotherDay';
        day.dayNum = i;
        days.push(day);
      }
      return [days.slice(0, 7), days.slice(7, 14), days.slice(14, 21), days.slice(21, 28), days.slice(28, 35), days.length > 35 ? days.slice(35, +(days.length - 1) + 1 || 9e9) : void 0];
    }).property('selectedDay', 'selectedMonth', 'selectedYear')
  });

}).call(this);
